name: Example Sent notification to email
on:
  push:
    branches:
      - "prod"

env:
  AWS_REGION: us-east-1                 
  ENV: "prod"

jobs:
  notif:
    name: Sent Notification
    runs-on: ubuntu-latest
    environment: Production
    steps:    
    - name: Publish Message To SNS Subscribers
      env:
        TOPIC_ARN: ${{ secrets.AWS_SNS_ARN }}
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
        aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
        aws sns publish --topic-arn $TOPIC_ARN --subject "Hello, from Indonesia" --message "New Version Is Released"
       
